dist: trusty
language: cpp
os: linux
sudo: required
compiler: g++
branches:
        only:
                - Template_Migration
addons:
        apt:
                sources:
                        - ubuntu-toolchain-r-test
                packages:
                        - g++-6
                        - cmake 
script: 
        - g++ -v && cmake --version
