dist: trusty
language: cpp
os: linux
sudo: required
compiler: g++
services:
        - docker
addons:
        apt:
                sources:
                        - ubuntu-toolchain-r-test
                packages:
                        - g++-6
                        - cmake
install:
        - docker build -t oogiya/myvector
before_script:
        - docker build --tag development -f Dockerfile.dev . 
script: 
        - docker run oogiya/myvector $project
        - g++ -v && cmake --version
