# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/miyu/git_workspace/Vector

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/miyu/git_workspace/Vector

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/miyu/git_workspace/Vector/CMakeFiles /home/miyu/git_workspace/Vector/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/miyu/git_workspace/Vector/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Vector

# Build rule for target.
Vector: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Vector
.PHONY : Vector

# fast build rule for target.
Vector/fast:
	$(MAKE) -f CMakeFiles/Vector.dir/build.make CMakeFiles/Vector.dir/build
.PHONY : Vector/fast

src/Container.o: src/Container.cpp.o

.PHONY : src/Container.o

# target to build an object file
src/Container.cpp.o:
	$(MAKE) -f CMakeFiles/Vector.dir/build.make CMakeFiles/Vector.dir/src/Container.cpp.o
.PHONY : src/Container.cpp.o

src/Container.i: src/Container.cpp.i

.PHONY : src/Container.i

# target to preprocess a source file
src/Container.cpp.i:
	$(MAKE) -f CMakeFiles/Vector.dir/build.make CMakeFiles/Vector.dir/src/Container.cpp.i
.PHONY : src/Container.cpp.i

src/Container.s: src/Container.cpp.s

.PHONY : src/Container.s

# target to generate assembly for a file
src/Container.cpp.s:
	$(MAKE) -f CMakeFiles/Vector.dir/build.make CMakeFiles/Vector.dir/src/Container.cpp.s
.PHONY : src/Container.cpp.s

src/Vector.o: src/Vector.cpp.o

.PHONY : src/Vector.o

# target to build an object file
src/Vector.cpp.o:
	$(MAKE) -f CMakeFiles/Vector.dir/build.make CMakeFiles/Vector.dir/src/Vector.cpp.o
.PHONY : src/Vector.cpp.o

src/Vector.i: src/Vector.cpp.i

.PHONY : src/Vector.i

# target to preprocess a source file
src/Vector.cpp.i:
	$(MAKE) -f CMakeFiles/Vector.dir/build.make CMakeFiles/Vector.dir/src/Vector.cpp.i
.PHONY : src/Vector.cpp.i

src/Vector.s: src/Vector.cpp.s

.PHONY : src/Vector.s

# target to generate assembly for a file
src/Vector.cpp.s:
	$(MAKE) -f CMakeFiles/Vector.dir/build.make CMakeFiles/Vector.dir/src/Vector.cpp.s
.PHONY : src/Vector.cpp.s

src/VectorClass.o: src/VectorClass.cpp.o

.PHONY : src/VectorClass.o

# target to build an object file
src/VectorClass.cpp.o:
	$(MAKE) -f CMakeFiles/Vector.dir/build.make CMakeFiles/Vector.dir/src/VectorClass.cpp.o
.PHONY : src/VectorClass.cpp.o

src/VectorClass.i: src/VectorClass.cpp.i

.PHONY : src/VectorClass.i

# target to preprocess a source file
src/VectorClass.cpp.i:
	$(MAKE) -f CMakeFiles/Vector.dir/build.make CMakeFiles/Vector.dir/src/VectorClass.cpp.i
.PHONY : src/VectorClass.cpp.i

src/VectorClass.s: src/VectorClass.cpp.s

.PHONY : src/VectorClass.s

# target to generate assembly for a file
src/VectorClass.cpp.s:
	$(MAKE) -f CMakeFiles/Vector.dir/build.make CMakeFiles/Vector.dir/src/VectorClass.cpp.s
.PHONY : src/VectorClass.cpp.s

src/VectorStruct.o: src/VectorStruct.cpp.o

.PHONY : src/VectorStruct.o

# target to build an object file
src/VectorStruct.cpp.o:
	$(MAKE) -f CMakeFiles/Vector.dir/build.make CMakeFiles/Vector.dir/src/VectorStruct.cpp.o
.PHONY : src/VectorStruct.cpp.o

src/VectorStruct.i: src/VectorStruct.cpp.i

.PHONY : src/VectorStruct.i

# target to preprocess a source file
src/VectorStruct.cpp.i:
	$(MAKE) -f CMakeFiles/Vector.dir/build.make CMakeFiles/Vector.dir/src/VectorStruct.cpp.i
.PHONY : src/VectorStruct.cpp.i

src/VectorStruct.s: src/VectorStruct.cpp.s

.PHONY : src/VectorStruct.s

# target to generate assembly for a file
src/VectorStruct.cpp.s:
	$(MAKE) -f CMakeFiles/Vector.dir/build.make CMakeFiles/Vector.dir/src/VectorStruct.cpp.s
.PHONY : src/VectorStruct.cpp.s

src/Vector_Container.o: src/Vector_Container.cpp.o

.PHONY : src/Vector_Container.o

# target to build an object file
src/Vector_Container.cpp.o:
	$(MAKE) -f CMakeFiles/Vector.dir/build.make CMakeFiles/Vector.dir/src/Vector_Container.cpp.o
.PHONY : src/Vector_Container.cpp.o

src/Vector_Container.i: src/Vector_Container.cpp.i

.PHONY : src/Vector_Container.i

# target to preprocess a source file
src/Vector_Container.cpp.i:
	$(MAKE) -f CMakeFiles/Vector.dir/build.make CMakeFiles/Vector.dir/src/Vector_Container.cpp.i
.PHONY : src/Vector_Container.cpp.i

src/Vector_Container.s: src/Vector_Container.cpp.s

.PHONY : src/Vector_Container.s

# target to generate assembly for a file
src/Vector_Container.cpp.s:
	$(MAKE) -f CMakeFiles/Vector.dir/build.make CMakeFiles/Vector.dir/src/Vector_Container.cpp.s
.PHONY : src/Vector_Container.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... Vector"
	@echo "... edit_cache"
	@echo "... src/Container.o"
	@echo "... src/Container.i"
	@echo "... src/Container.s"
	@echo "... src/Vector.o"
	@echo "... src/Vector.i"
	@echo "... src/Vector.s"
	@echo "... src/VectorClass.o"
	@echo "... src/VectorClass.i"
	@echo "... src/VectorClass.s"
	@echo "... src/VectorStruct.o"
	@echo "... src/VectorStruct.i"
	@echo "... src/VectorStruct.s"
	@echo "... src/Vector_Container.o"
	@echo "... src/Vector_Container.i"
	@echo "... src/Vector_Container.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

